### ISSUE TITLE
Does not compile/work, missing files

### ISSUE THREAD

**Issue by ericalbers** [guythiebaut/TeboCam_OpenSource#1]
When trying to open TeboCam.sln in visual studio, there are files/projects missing:

vfw.csproj is missing, heres the exact error when opening from the git cloned directory...

C:\TeboCam_OpenSource\TeboCam\TeboCam.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\TeboCam_OpenSource\TeboCam\TeboCam.csproj'.  C:\TeboCam_OpenSource\TeboCam\TeboCam.csproj

C:\TeboCam_OpenSource\vfw\vfw.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\TeboCam_OpenSource\vfw\vfw.csproj'.  C:\TeboCam_OpenSource\vfw\vfw.csproj

**Comment by guythiebaut** [comment]
You won't need to access vfw, so for the moment I suggest that you just comment out anything that refers to this - it is a library that provides avi recording methods(not implemented in TeboCam).

**Comment by ericalbers** [comment]
Not so easy to do, its the solution file which refers to it, so when you open in visual studio, TeboCam, and vfw both come up as unavailable.
See image attached of VS on trying to load solution


![teboerr](https://cloud.githubusercontent.com/assets/2427898/12222264/6414893e-b785-11e5-802b-096d55fa9906.png)
